### ISSUE TITLE
Move from maven to gradle

### ISSUE THREAD

**Issue by TijoloAzul** [dinis/raspberryGameSuite#4]
I'm creating this issue because we were saying that you wanted to use gradle... as you wish.
I'll see if it is easy.

**Comment by diogodinisf** [comment]
For me, at this time, is equal. But gradle is the default for Android, that is us final goal on the client side. 
I don't know if it is easy, but theoretically has the best of Maven.

**Comment by TijoloAzul** [comment]
please change README and close this issue

**Comment by diogodinisf** [comment]
I can already build the dependencies with the gradle. 
I think we can remove "all" maven things of the projetc.
Of course that gradle use maven because... maven is maven.

**Comment by diogodinisf** [comment]
Sorry, I change de garbage label colour and I don't remember its original colour. Sorry, I know that colours are very important to you...

**Comment by TijoloAzul** [comment]
Please, do create a branch where you remove all maven stuff and do a pull request.
